name: Hunter

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  hunter:
    runs-on: ubuntu-latest

    steps:
      - name: Scarica il progetto
        uses: actions/checkout@v5

      - name: Installa Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Avvia Hunter
        run: python hunter.py
